# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160412_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=datetime.datetime(2016, 7, 29, 18, 16, 53, 836347, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
